# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a470766e7abb6f5835fec0e2e5f220a4ba3b40cefc38326dfd550f49ca4d09bbd229998f883e6b8c906322f4a43648cc0c48700e29faa32bfcf51921c2cdfd4c

test:
  secret_key_base: 4f0d650597c21f4a8166d9b293f4a97e95833c8a2d897f958617372238cf2e7eedc3bfd91871adbbcfed25d45d6e98cf9218ce236f48347184a503447c1e48a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
